name: Lint Backend

on: [ push, pull_request ]

jobs:
  lint-backend:
    name: Lint Java using Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download Checkstyle
        run: |
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar

      - name: Download Google Checks Rules
        run: |
          curl -L -o google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c google_checks.xml app/src/main/java/com/project/back_end || true